
name: Mantenimiento

on:
  schedule:
    - cron: '0 3 * * 0'  # Cada domingo
  workflow_dispatch:

jobs:
  mantenimiento:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mantenimiento
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ci-cd-app:patch-${{ github.run_number }} .
          docker push ghcr.io/${{ github.repository_owner }}/ci-cd-app:patch-${{ github.run_number }}

