name: Deploy Monitoreo

on:
  workflow_dispatch:

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker compose -f docker-compose.yml up -d
docker-compose.yml:

version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
